config/routes.rb
Rails.application.routes.draw do

  get 'strategy',to: 'strategy#index',as: 'strategy'
    get 'strategy/forecheck',to: 'strategy#forecheck'
    get 'strategy/entry',to: 'strategy#entry'
    get 'strategy/odd-man-rush',to: 'strategy#odd_man_rush'
    get 'strategy/powerplay',to: 'strategy#powerplay'
    get 'strategy/breakout',to: 'strategy#breakout'

  get 'dashboard',to: 'dashboard#index',as: 'dashboard'

  get 'signup/index'

  resources :users
  
  root 'dashboard#index'

  get '/access/normal',to: 'sessions#new',as: 'login'
  post '/access/normal',to: 'sessions#create',as: 'login_try'
  get '/access/logout',to: 'sessions#destroy',as: 'logout'

  get '/access/signup',to: 'signup#index',as: 'signup'
  post '/access/signup',to: 'signup#create',as: 'new_signup'

  get 'angularjs/templates/:page',to: 'angularjs#index'

  # API
  namespace :api do
    namespace :v1 do

      # API INSERT
			resources :player#,path: 'players'
      put :player,to: 'player#update'
			resources :playlist,path: 'playlists'
      get 'soundcloud/tracks',to: 'soundcloud#tracks'
			resources :soundcloud,path: 'soundcloud'
			resources :comment,path: 'comments'
			resources :user,path: 'users'

    end
  end
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= TITLE %></title>
	<script type="text/javascript">var current_user = <%= current_user.to_json(except: :password_digest).html_safe %>;</script>
	<link rel="shortcut icon" href="<%= asset_path 'logo.png' %>" />
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body ng:controller="Ctrl">

	<nav class="navbar navbar-default">
		<div class="container">

			<div class="navbar-header">
				<div class="container-fluid">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<%= link_to dashboard_path,class: 'navbar-brand' do %>
					<span><%= image_tag 'logo.png',height: 20 %></span>
					<% end %>
				</div>
			</div>

			<div class="collapse navbar-collapse" id="navbar">
				<ul class="nav navbar-nav">
					<li></li>
					<!-- <li><%= link_to 'Members',users_path %></li> -->
					<li><%= link_to 'Strategy',strategy_path %></li>
					<li><%= link_to 'Sticks on Outside Diagram',asset_path('display-stick-side-A.png'),target: '_blank' %></li>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<li></li>
				</ul>
			</div>
			
		</div>
	</nav>

	<div class="container" ng:show="loaded">

		<!--<script src="//connect.soundcloud.com/sdk-2.0.0.js"></script>-->
		<!-- <soundcloud></soundcloud> -->

		<% flash.each do |type,message| %>
		<alert type="<%= type %>"><%= message %></alert>
		<% end %>

		<!-- <div plangular="https://soundcloud.com/highbrow-lowstache/the-notorious-b-i-g-machine">

			<div class="alert alert-info forever" role="alert">

				<div class="row">
					<div class="col-md-12">

						<button class="btn btn-default btn-lg" ng:click=""><%= icon 'step-backward' %></button>

						<button class="btn btn-default btn-lg" ng:click="play(); playing = true" ng:show="!playing"><%= icon 'play' %></button>

						<button class="btn btn-warning btn-lg" ng:click="pause(); playing = false" ng:show="playing"><%= icon 'pause' %></button>

						<button class="btn btn-default btn-lg" ng:click=""><%= icon 'step-forward' %></button>

						&nbsp;&nbsp;

						{{ currentTime | hhmmss }}&nbsp;/&nbsp;{{ duration | hhmmss }}

						&nbsp;&nbsp;

						<a href="https://soundcloud.com/highbrow-lowstache/the-notorious-b-i-g-machine" target="_blank">{{track.title}}</a>

					</div>
				</div>

			</div>

		</div> -->

		<%= yield %>

	</div>

</body>
</html>

app/views/layouts/splash.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= TITLE %></title>
	<script type="text/javascript">var current_user = <%= current_user.to_json(except: :password_digest).html_safe %>;</script>
	<link rel="shortcut icon" href="<%= asset_path 'logo.png' %>" />
	<%= stylesheet_link_tag    'splash', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'splash', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body ng:controller="Ctrl">

	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">

			<div class="navbar-header">
				<div class="container-fluid">
					<%= link_to root_path,class: 'navbar-brand' do %>
					<span><%= image_tag 'logo.png',height: 20 %></span>
					&nbsp;&nbsp;WEST COAST AVENGERS
					<% end %>
				</div>
			</div>

			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li></li>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to login_path do %><%= icon 'log-in' %>&nbsp;&nbsp;Log In<% end %></li>
				</ul>
			</div>
			
		</div>
	</nav>
	
	<%= yield %>

</body>
</html>